plugins {
    id 'java'
    id 'application'
    // id 'org.javamodularity.moduleplugin' version '1.8.12'
    id 'org.openjfx.javafxplugin' version '0.0.14'
    id 'org.beryx.jlink' version '2.25.0'
}

group 'io.github.kaizensphere.devin'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.10.2'
}

configurations {
    mockitoAgent
}


sourceCompatibility = '23'
targetCompatibility = '23'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

application {
    // mainModule = 'dev.kaizensphere.devin.desktop'
    mainClass = 'dev.kaizensphere.devin.desktop.DevinGUI'
}



javafx {
    version = '23.0.1'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.web', 'javafx.swing']
}

dependencies {

    implementation project(":core")

    implementation('org.controlsfx:controlsfx:11.2.1')
    implementation('com.dlsc.formsfx:formsfx-core:11.6.0') {
        exclude(group: 'org.openjfx')
    }
    implementation('net.synedra:validatorfx:0.5.0') {
        exclude(group: 'org.openjfx')
    }
    implementation('org.kordamp.ikonli:ikonli-javafx:12.3.1')
    // https://mvnrepository.com/artifact/org.kordamp.ikonli/ikonli-fontawesome5-pack
    implementation("org.kordamp.ikonli:ikonli-fontawesome5-pack:12.3.1")
    // https://mvnrepository.com/artifact/io.github.mkpaz/atlantafx-base
    implementation("io.github.mkpaz:atlantafx-base:2.0.1")

    implementation('eu.hansolo:tilesfx:21.0.3') {
        exclude(group: 'org.openjfx')
    }

    // https://mvnrepository.com/artifact/org.fxmisc.wellbehaved/wellbehavedfx
    implementation("org.fxmisc.wellbehaved:wellbehavedfx:0.3.3")

    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation("org.mockito:mockito-core:5.17.0")
    // https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter
    testImplementation("org.mockito:mockito-junit-jupiter:5.17.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")

    mockitoAgent("org.mockito:mockito-core:5.17.0") {
        transitive = false
    }
}

test {
    useJUnitPlatform()
    jvmArgs += "-javaagent:${configurations.mockitoAgent.singleFile}"
}

//jlink {
//    imageZip = project.file("${buildDir}/distributions/app-${javafx.platform.classifier}.zip")
//    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
//    launcher {
//        name = 'app'
//    }
//}
//
//jlinkZip {
//    group = 'distribution'
//}